OMGHAI!
-------- day 0 --------
name, sellIn, quality
Aged Brie, 5, 10
Aged Brie, 5, 11

-------- day 1 --------
name, sellIn, quality
Aged Brie, 4, 11
Aged Brie, 4, 12

-------- day 2 --------
name, sellIn, quality
Aged Brie, 3, 12
Aged Brie, 3, 13

-------- day 3 --------
name, sellIn, quality
Aged Brie, 2, 13
Aged Brie, 2, 14

-------- day 4 --------
name, sellIn, quality
Aged Brie, 1, 14
Aged Brie, 1, 15

-------- day 5 --------
name, sellIn, quality
Aged Brie, 0, 15
Aged Brie, 0, 16

-------- day 6 --------
name, sellIn, quality
Aged Brie, -1, 17
Aged Brie, -1, 18

-------- day 7 --------
name, sellIn, quality
Aged Brie, -2, 19
Aged Brie, -2, 20

-------- day 8 --------
name, sellIn, quality
Aged Brie, -3, 21
Aged Brie, -3, 22

-------- day 9 --------
name, sellIn, quality
Aged Brie, -4, 23
Aged Brie, -4, 24

-------- day 10 --------
name, sellIn, quality
Aged Brie, -5, 25
Aged Brie, -5, 26

-------- day 11 --------
name, sellIn, quality
Aged Brie, -6, 27
Aged Brie, -6, 28

-------- day 12 --------
name, sellIn, quality
Aged Brie, -7, 29
Aged Brie, -7, 30

-------- day 13 --------
name, sellIn, quality
Aged Brie, -8, 31
Aged Brie, -8, 32

-------- day 14 --------
name, sellIn, quality
Aged Brie, -9, 33
Aged Brie, -9, 34

-------- day 15 --------
name, sellIn, quality
Aged Brie, -10, 35
Aged Brie, -10, 36

-------- day 16 --------
name, sellIn, quality
Aged Brie, -11, 37
Aged Brie, -11, 38

-------- day 17 --------
name, sellIn, quality
Aged Brie, -12, 39
Aged Brie, -12, 40

-------- day 18 --------
name, sellIn, quality
Aged Brie, -13, 41
Aged Brie, -13, 42

-------- day 19 --------
name, sellIn, quality
Aged Brie, -14, 43
Aged Brie, -14, 44

-------- day 20 --------
name, sellIn, quality
Aged Brie, -15, 45
Aged Brie, -15, 46

-------- day 21 --------
name, sellIn, quality
Aged Brie, -16, 47
Aged Brie, -16, 48

-------- day 22 --------
name, sellIn, quality
Aged Brie, -17, 49
Aged Brie, -17, 50

-------- day 23 --------
name, sellIn, quality
Aged Brie, -18, 50
Aged Brie, -18, 50

-------- day 24 --------
name, sellIn, quality
Aged Brie, -19, 50
Aged Brie, -19, 50

-------- day 25 --------
name, sellIn, quality
Aged Brie, -20, 50
Aged Brie, -20, 50

