OMGHAI!
-------- day 0 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

-------- day 1 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

-------- day 2 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

-------- day 3 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

-------- day 4 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

-------- day 5 --------
name, sellIn, quality
Sulfuras, Hand of Ragnaros, 0, 80

