OMGHAI!
-------- day 0 --------
name, sellIn, quality
Dexterity Vest, 5, 10

-------- day 1 --------
name, sellIn, quality
Dexterity Vest, 4, 9

-------- day 2 --------
name, sellIn, quality
Dexterity Vest, 3, 8

-------- day 3 --------
name, sellIn, quality
Dexterity Vest, 2, 7

-------- day 4 --------
name, sellIn, quality
Dexterity Vest, 1, 6

-------- day 5 --------
name, sellIn, quality
Dexterity Vest, 0, 5

