OMGHAI!
-------- day 0 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 15, 46
Backstage passes to a TAFKAL80ETC concert, 15, 41
Backstage passes to a TAFKAL80ETC concert, 15, 40
Backstage passes to a TAFKAL80ETC concert, 15, 39
Backstage passes to a TAFKAL80ETC concert, 15, 30
Backstage passes to a TAFKAL80ETC concert, 15, 29
Backstage passes to a TAFKAL80ETC concert, 15, 28
Backstage passes to a TAFKAL80ETC concert, 15, 20
Backstage passes to a TAFKAL80ETC concert, 15, 19
Backstage passes to a TAFKAL80ETC concert, 15, 18

-------- day 1 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 14, 47
Backstage passes to a TAFKAL80ETC concert, 14, 42
Backstage passes to a TAFKAL80ETC concert, 14, 41
Backstage passes to a TAFKAL80ETC concert, 14, 40
Backstage passes to a TAFKAL80ETC concert, 14, 31
Backstage passes to a TAFKAL80ETC concert, 14, 30
Backstage passes to a TAFKAL80ETC concert, 14, 29
Backstage passes to a TAFKAL80ETC concert, 14, 21
Backstage passes to a TAFKAL80ETC concert, 14, 20
Backstage passes to a TAFKAL80ETC concert, 14, 19

-------- day 2 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 13, 48
Backstage passes to a TAFKAL80ETC concert, 13, 43
Backstage passes to a TAFKAL80ETC concert, 13, 42
Backstage passes to a TAFKAL80ETC concert, 13, 41
Backstage passes to a TAFKAL80ETC concert, 13, 32
Backstage passes to a TAFKAL80ETC concert, 13, 31
Backstage passes to a TAFKAL80ETC concert, 13, 30
Backstage passes to a TAFKAL80ETC concert, 13, 22
Backstage passes to a TAFKAL80ETC concert, 13, 21
Backstage passes to a TAFKAL80ETC concert, 13, 20

-------- day 3 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 12, 49
Backstage passes to a TAFKAL80ETC concert, 12, 44
Backstage passes to a TAFKAL80ETC concert, 12, 43
Backstage passes to a TAFKAL80ETC concert, 12, 42
Backstage passes to a TAFKAL80ETC concert, 12, 33
Backstage passes to a TAFKAL80ETC concert, 12, 32
Backstage passes to a TAFKAL80ETC concert, 12, 31
Backstage passes to a TAFKAL80ETC concert, 12, 23
Backstage passes to a TAFKAL80ETC concert, 12, 22
Backstage passes to a TAFKAL80ETC concert, 12, 21

-------- day 4 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 11, 50
Backstage passes to a TAFKAL80ETC concert, 11, 45
Backstage passes to a TAFKAL80ETC concert, 11, 44
Backstage passes to a TAFKAL80ETC concert, 11, 43
Backstage passes to a TAFKAL80ETC concert, 11, 34
Backstage passes to a TAFKAL80ETC concert, 11, 33
Backstage passes to a TAFKAL80ETC concert, 11, 32
Backstage passes to a TAFKAL80ETC concert, 11, 24
Backstage passes to a TAFKAL80ETC concert, 11, 23
Backstage passes to a TAFKAL80ETC concert, 11, 22

-------- day 5 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 10, 50
Backstage passes to a TAFKAL80ETC concert, 10, 46
Backstage passes to a TAFKAL80ETC concert, 10, 45
Backstage passes to a TAFKAL80ETC concert, 10, 44
Backstage passes to a TAFKAL80ETC concert, 10, 35
Backstage passes to a TAFKAL80ETC concert, 10, 34
Backstage passes to a TAFKAL80ETC concert, 10, 33
Backstage passes to a TAFKAL80ETC concert, 10, 25
Backstage passes to a TAFKAL80ETC concert, 10, 24
Backstage passes to a TAFKAL80ETC concert, 10, 23

-------- day 6 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 9, 50
Backstage passes to a TAFKAL80ETC concert, 9, 48
Backstage passes to a TAFKAL80ETC concert, 9, 47
Backstage passes to a TAFKAL80ETC concert, 9, 46
Backstage passes to a TAFKAL80ETC concert, 9, 37
Backstage passes to a TAFKAL80ETC concert, 9, 36
Backstage passes to a TAFKAL80ETC concert, 9, 35
Backstage passes to a TAFKAL80ETC concert, 9, 27
Backstage passes to a TAFKAL80ETC concert, 9, 26
Backstage passes to a TAFKAL80ETC concert, 9, 25

-------- day 7 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 8, 50
Backstage passes to a TAFKAL80ETC concert, 8, 50
Backstage passes to a TAFKAL80ETC concert, 8, 49
Backstage passes to a TAFKAL80ETC concert, 8, 48
Backstage passes to a TAFKAL80ETC concert, 8, 39
Backstage passes to a TAFKAL80ETC concert, 8, 38
Backstage passes to a TAFKAL80ETC concert, 8, 37
Backstage passes to a TAFKAL80ETC concert, 8, 29
Backstage passes to a TAFKAL80ETC concert, 8, 28
Backstage passes to a TAFKAL80ETC concert, 8, 27

-------- day 8 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 7, 50
Backstage passes to a TAFKAL80ETC concert, 7, 50
Backstage passes to a TAFKAL80ETC concert, 7, 50
Backstage passes to a TAFKAL80ETC concert, 7, 50
Backstage passes to a TAFKAL80ETC concert, 7, 41
Backstage passes to a TAFKAL80ETC concert, 7, 40
Backstage passes to a TAFKAL80ETC concert, 7, 39
Backstage passes to a TAFKAL80ETC concert, 7, 31
Backstage passes to a TAFKAL80ETC concert, 7, 30
Backstage passes to a TAFKAL80ETC concert, 7, 29

-------- day 9 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 6, 50
Backstage passes to a TAFKAL80ETC concert, 6, 50
Backstage passes to a TAFKAL80ETC concert, 6, 50
Backstage passes to a TAFKAL80ETC concert, 6, 50
Backstage passes to a TAFKAL80ETC concert, 6, 43
Backstage passes to a TAFKAL80ETC concert, 6, 42
Backstage passes to a TAFKAL80ETC concert, 6, 41
Backstage passes to a TAFKAL80ETC concert, 6, 33
Backstage passes to a TAFKAL80ETC concert, 6, 32
Backstage passes to a TAFKAL80ETC concert, 6, 31

-------- day 10 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 5, 50
Backstage passes to a TAFKAL80ETC concert, 5, 50
Backstage passes to a TAFKAL80ETC concert, 5, 50
Backstage passes to a TAFKAL80ETC concert, 5, 50
Backstage passes to a TAFKAL80ETC concert, 5, 45
Backstage passes to a TAFKAL80ETC concert, 5, 44
Backstage passes to a TAFKAL80ETC concert, 5, 43
Backstage passes to a TAFKAL80ETC concert, 5, 35
Backstage passes to a TAFKAL80ETC concert, 5, 34
Backstage passes to a TAFKAL80ETC concert, 5, 33

-------- day 11 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 4, 50
Backstage passes to a TAFKAL80ETC concert, 4, 50
Backstage passes to a TAFKAL80ETC concert, 4, 50
Backstage passes to a TAFKAL80ETC concert, 4, 50
Backstage passes to a TAFKAL80ETC concert, 4, 48
Backstage passes to a TAFKAL80ETC concert, 4, 47
Backstage passes to a TAFKAL80ETC concert, 4, 46
Backstage passes to a TAFKAL80ETC concert, 4, 38
Backstage passes to a TAFKAL80ETC concert, 4, 37
Backstage passes to a TAFKAL80ETC concert, 4, 36

-------- day 12 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 50
Backstage passes to a TAFKAL80ETC concert, 3, 49
Backstage passes to a TAFKAL80ETC concert, 3, 41
Backstage passes to a TAFKAL80ETC concert, 3, 40
Backstage passes to a TAFKAL80ETC concert, 3, 39

-------- day 13 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 50
Backstage passes to a TAFKAL80ETC concert, 2, 44
Backstage passes to a TAFKAL80ETC concert, 2, 43
Backstage passes to a TAFKAL80ETC concert, 2, 42

-------- day 14 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 50
Backstage passes to a TAFKAL80ETC concert, 1, 47
Backstage passes to a TAFKAL80ETC concert, 1, 46
Backstage passes to a TAFKAL80ETC concert, 1, 45

-------- day 15 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 50
Backstage passes to a TAFKAL80ETC concert, 0, 49
Backstage passes to a TAFKAL80ETC concert, 0, 48

-------- day 16 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0
Backstage passes to a TAFKAL80ETC concert, -1, 0

-------- day 17 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0
Backstage passes to a TAFKAL80ETC concert, -2, 0

-------- day 18 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0
Backstage passes to a TAFKAL80ETC concert, -3, 0

-------- day 19 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0
Backstage passes to a TAFKAL80ETC concert, -4, 0

-------- day 20 --------
name, sellIn, quality
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0
Backstage passes to a TAFKAL80ETC concert, -5, 0

